version: '3.1'
services :
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payslips_db
  admin:
    image: adminer
    restart: always
    ports:
      - 8081:8080